services:
    nginx:
      build:
        context: .
        dockerfile: "dockerfile.nginx"
      ports:
        - 80:80
        - 443:443
      links:
        - books

    books:
        build:
          context: .
        container_name: books
        command: sh -c "fastapi run app/main.py --port 80"